// widgets/countries-angular/src/main.ts
import { createApplication } from "@angular/platform-browser";
import { provideZonelessChangeDetection } from "@angular/core";
import { AppComponent } from "./app/app.component";
import type { WidgetSDK } from "./types";

let initialized = false;

export async function init(sdk: WidgetSDK) {
  if (initialized) return;
  initialized = true;
  await sdk.whenReady();
  const host = document.createElement("countries-angular-root");
  const appRef = await createApplication({
    providers: [provideZonelessChangeDetection()],
  });
  appRef.bootstrap(AppComponent, host);
  sdk.getContainer().appendChild(host);
  sdk.on("destroy", () => {
    initialized = false;
    appRef.destroy();
    host.remove();
  });
}

// widgets/pokemon-search/src/main.tsx
import "./setup-dev";
import { createRoot } from "react-dom/client";
import { App } from "./App";
import type { WidgetSDK } from "./types";

export async function init(sdk: WidgetSDK) {
  await sdk.whenReady();

  const root = createRoot(sdk.getContainer());
  root.render(<App sdk={sdk} />);
  sdk.on("destroy", () => root.unmount());
}
