// widgets/countries-react/src/main.tsx
import "./widget.css";
import "./setup-dev";
import { createRoot } from "react-dom/client";
import { App } from "./App";
import type { WidgetSDK } from "./types";
import { HEADER_PROP } from "./constants";

const extractHeader = (sdk: WidgetSDK) => {
  const v = sdk.getProps()[HEADER_PROP];
  return typeof v === "string" ? v : "";
};

export async function init(sdk: WidgetSDK) {
  await sdk.whenReady();
  const link = document.createElement("link");
  link.rel = "stylesheet";
  const cssReady = new Promise<void>((resolve) => {
    link.onload = () => resolve();
    link.onerror = () => resolve();
  });
  link.href = new URL("./widget.css", import.meta.url).href;
  sdk.shadowRoot.insertBefore(link, sdk.shadowRoot.firstChild);
  const root = createRoot(sdk.getContainer());
  await cssReady;
  root.render(<App header={extractHeader(sdk)} />);
  const unsubscribeProps = sdk.on("propsChanged", () => root.render(<App header={extractHeader(sdk)} />));
  sdk.on("destroy", () => {
    unsubscribeProps();
    root.unmount();
  });
}

// widgets/countries-angular/src/main.ts
import { createApplication } from "@angular/platform-browser";
import { provideZonelessChangeDetection } from "@angular/core";
import { AppComponent } from "./app/app.component";
import { WIDGET_SDK_TOKEN, type WidgetSDK } from "./types";

let initialized = false;

export async function init(sdk: WidgetSDK) {
  if (initialized) return;
  initialized = true;
  await sdk.whenReady();
  const host = document.createElement("countries-angular-root");
  host.style.visibility = "hidden";
  const appRef = await createApplication({
    providers: [
      provideZonelessChangeDetection(),
      { provide: WIDGET_SDK_TOKEN, useValue: sdk },
    ],
  });
  appRef.bootstrap(AppComponent, host);
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.onload = () => (host.style.visibility = "");
  link.onerror = () => (host.style.visibility = "");
  host.shadowRoot!.insertBefore(link, host.shadowRoot!.firstChild);
  link.href = new URL("./widget.css", import.meta.url).href;
  sdk.getContainer().appendChild(host);
  sdk.on("destroy", () => {
    initialized = false;
    appRef.destroy();
    host.remove();
  });
}
