// widgets/countries-react/src/App.tsx
import { useCountries } from "./hooks/useCountries";
import { CountryCard } from "./CountryCard";
import { TOP_COUNTRIES_COUNT } from "./constants";

const SKELETON_KEYS = Array.from({ length: TOP_COUNTRIES_COUNT }, (_, i) => i);

export const App = () => {
  const { countries, loading, error } = useCountries();

  return (
    <section className="react-widget-section">
      <p className="widget-framework-header">React</p>
      {loading && (
        <ul role="status" aria-label="Loading country data" className="country-list">
          {SKELETON_KEYS.map((i) => (
            <li key={i} className="country-item country-item--skeleton">
              <div className="country-flag country-flag--skeleton" />
              <div className="country-details">
                <div className="country-skeleton-line country-skeleton-line--name" />
                <div className="country-skeleton-line country-skeleton-line--meta" />
              </div>
            </li>
          ))}
        </ul>
      )}
      {!loading && error && (
        <div role="alert" className="country-error">
          <p>{error}</p>
        </div>
      )}
      {!loading && !error && (
        <ul className="country-list">
          {countries.map((c) => (
            <CountryCard key={c.name} country={c} />
          ))}
        </ul>
      )}
    </section>
  );
};

// widgets/countries-vue/src/App.vue
<script setup lang="ts">
import { useCountries } from "./composables/useCountries";
import CountryCard from "./CountryCard.vue";
import { TOP_COUNTRIES_COUNT } from "./constants";

const { countries, loading, error } = useCountries();
</script>

<template>
  <section class="vue-widget-section">
    <p class="widget-framework-header">Vue</p>
    <ul v-if="loading" role="status" aria-label="Loading country data" class="country-list">
      <li v-for="n in TOP_COUNTRIES_COUNT" :key="n" class="country-item country-item--skeleton">
        <div class="country-flag country-flag--skeleton" />
        <div class="country-details">
          <div class="country-skeleton-line country-skeleton-line--name" />
          <div class="country-skeleton-line country-skeleton-line--meta" />
        </div>
      </li>
    </ul>
    <div v-else-if="error" role="alert" class="country-error">
      <p>{{ error }}</p>
    </div>
    <ul v-else class="country-list">
      <CountryCard v-for="c in countries" :key="c.name" :country="c" />
    </ul>
  </section>
</template>
