// widgets/countries-angular/src/app/country-card.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import type { Country } from "../types";

@Component({
  selector: "app-country-card",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <li class="country-item" [attr.aria-label]="country().name">
      <img
        class="country-flag"
        [src]="country().flag"
        [alt]="'Flag of ' + country().name"
        (error)="onFlagError($event)"
      />
      <div class="country-details">
        <span class="country-name">{{ country().name }}</span>
        <span class="country-meta">{{ country().capital }} · {{ formattedPopulation() }} · {{ country().region }}</span>
      </div>
    </li>
  `,
})
export class CountryCardComponent {
  readonly country = input.required<Country>();

  readonly formattedPopulation = computed(() => this.country().population.toLocaleString("en-US"));

  onFlagError(e: Event): void {
    if (e.currentTarget instanceof HTMLImageElement) e.currentTarget.style.opacity = "0";
  }
}

// widgets/countries-vue/src/CountryCard.vue
<script setup lang="ts">
import type { Country } from "./types";

defineProps<{ country: Country }>();

const onFlagError = (e: Event) => {
  if (e.currentTarget instanceof HTMLImageElement) e.currentTarget.style.opacity = "0";
};
</script>

<template>
  <li class="country-item" :aria-label="country.name">
    <img
      class="country-flag"
      :src="country.flag"
      :alt="`Flag of ${country.name}`"
      @error="onFlagError"
    />
    <div class="country-details">
      <span class="country-name">{{ country.name }}</span>
      <span class="country-meta">{{ country.capital }} · {{ country.population.toLocaleString("en-US") }} · {{ country.region }}</span>
    </div>
  </li>
</template>
